eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/
server:
  port: 7999

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/lingdi0/LEurekaConfig
          searchPaths: config
  application:
    name: config-server